# Use the base TensorRT image
FROM nvcr.io/nvidia/l4t-tensorrt:r10.3.0-devel

WORKDIR /usr/src

RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu126

RUN sed -i 's/^import tensorrt/# import tensorrt/' setup.py && \
    sed -i 's/version.parse(tensorrt.__version__)/version.parse("8")/' setup.py
RUN perl -pi -e 'if (/plugins_ext_module = CUDAExtension\(/../^\s*\)/) { s/^/#/ }' setup.py
RUN python3 setup.py install
RUN CUDA_HOME=/usr/local/cuda PATH=$CUDA_HOME/bin:$PATH python3 setup.py build_ext --inplace && \
    python3 setup.py install

# Update and install python3-venv, clone the repository, and run the setup script
RUN apt-get update && apt-get install -y \
    python3-venv \
    ffmpeg \
    git \
    && git clone --branch jetson-fix --recursive https://github.com/Emz-programmer/wyoming-whisper-trt \
    && cd wyoming-whisper-trt \
    && chmod +x ./script/setup \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY ./run.sh ./
    
EXPOSE 10300
    
ENTRYPOINT ["bash", "/run.sh"]
