# Use the base TensorRT image
FROM dustynv/whisper_trt:r36.3.0

WORKDIR /usr/src

# Update and install python3-venv, clone the repository, and run the setup script
RUN apt-get update && apt-get install -y \
    python3-venv \
    ffmpeg \
    git \
    && git clone -b release/1.0.10 --recursive https://github.com/Jonah-May-OSS/wyoming-whisper-trt \
    && cd wyoming-whisper-trt \
    && chmod +x ./script/setup \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY ./run-jetson.sh ./
    
EXPOSE 10300

RUN rm -rf /root/.cache/whisper
    
ENTRYPOINT ["bash", "/run-jetson.sh"]
