# Use the base TensorRT image
FROM dustynv/whisper_trt:r36.3.0

WORKDIR /usr/src

# Update and install python3-venv, clone the repository, and run the setup script
RUN apt-get update && apt-get install -y \
    python3-venv \
    ffmpeg \
    git \
    && git clone -b docker-for-jetson --recursive Emz-programmer/wyoming-whisper-trt \
    && cd wyoming-whisper-trt \
    && chmod +x ./script/setup \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY ./run.sh ./
    
EXPOSE 10300
    
ENTRYPOINT ["bash", "/run.sh"]
