# Use the base TensorRT image
FROM dustynv/torch2trt:r36.4.0-cu128-24.04

WORKDIR /usr/src

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all
ENV NVIDIA_REQUIRE_JETPACK_HOST_MOUNTS=base-only

ENV CUDA_HOME=/usr/local/cuda
ENV PATH=$CUDA_HOME/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu:${LD_LIBRARY_PATH}

# Update and install python3-venv, clone the repository, and run the setup script
RUN apt-get update && apt-get install -y \
    ffmpeg \
    git 

# Setup python deps
RUN pip3 install --index-url https://pypi.org/simple --extra-index-url https://pypi.nvidia.com \
    wyoming==1.8.0 \
    openai-whisper==20250625 \
    psutil~=7.2.1 \
    packaging~=26.0 \
    onnx~=1.19.1 \
    onnxscript~=0.5.6 \
    onnx-graphsurgeon==0.5.8 \
    huggingface_hub>=0.23 \
    pyyaml

# RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.26.0/bazelisk-linux-arm64 \
#     && mv bazelisk-linux-arm64 /usr/bin/bazel \
#     && chmod +x /usr/bin/bazel \
#     && apt-get install -y ninja-build vim libopenblas-dev \
#     && mkdir pytorch-trt

# WORKDIR /usr/src/pytorch-trt

# RUN git clone -b release/2.8 https://github.com/pytorch/TensorRT.git \
#     && cd TensorRT \
#     && python setup.py bdist_wheel --jetpack \
#     && pip3 install ./dist/*.whl

# RUN wget https://github.com/pytorch/TensorRT/releases/download/v2.8.0/torch_tensorrt-2.8.0+cu126-cp310-cp310-linux_aarch64.whl \
#     && pip3 install ./torch_tensorrt-2.8.0+cu126-cp310-cp310-linux_aarch64.whl

RUN git clone -b alt-jetson-approach --recursive https://github.com/Emz-programmer/wyoming-whisper-trt

WORKDIR /
COPY ./run.sh ./
    
EXPOSE 10300
    
ENTRYPOINT ["bash", "/run.sh"]
